routes/web.php
<?php

use App\Http\Controllers\Admin\AnakController;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\KeuanganController;
use App\Http\Controllers\Admin\PemasukanController;
use App\Http\Controllers\Admin\PengeluaranController;
use App\Http\Controllers\Admin\ProgramController as AdminProgramController;
use App\Http\Controllers\Admin\PengurusController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\CKEditorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\UserController as ControllersUserController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::get('/', [AdminHomeController::class, 'index'])->name('admin.index');
    Route::prefix('keuangan')->group(function(){
        Route::get('/', [KeuanganController::class, 'index'])->name('keuangan.index');
        Route::get('pemasukan', [PemasukanController::class, 'index'])->name('pemasukan.index');
        Route::resource('pengeluaran', PengeluaranController::class)->except('show');
    });
    Route::resource('program', AdminProgramController::class)->except('show');
    Route::resource('pengurus', PengurusController::class);
    Route::resource('anak', AnakController::class);
    Route::resource('role', RoleController::class);
    Route::resource('user', UserController::class)->except('show');
});

Route::post('ckeditor/upload', [CKEditorController::class, 'upload'])->name('ckeditor.image-upload');
Route::get('{user}/profile', [ControllersUserController::class, 'show'])->name('profile');
Route::get('{user}/invoice', [InvoiceController::class, 'index'])->name('index.invoice');
Route::get('{user}/invoice/{invoice}', [InvoiceController::class, 'show'])->name('show.invoice');
Route::get('donation/pay/{invoice}', [DonationController::class, 'snap'])->name('donation.pay');
Route::post('donation/hook', [DonationController::class, 'hook'])->name('donation.hook');
Route::prefix('program')->group(function(){
    Route::get('/', [ProgramController::class, 'index'])->name('user-program.index');
    Route::get('{program}', [ProgramController::class, 'show'])->name('user-program.show');
    Route::middleware(['auth'])->group(function () {
    Route::post('{program}/donation', [ProgramController::class, 'store'])->name('donation.store');
    });
});

Auth::routes();

Route::get('/', HomeController::class)->name('home');

Route::get('/sto', fn () => storage_path());

app/Models/Anak.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Anak extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Http/Controllers/Admin/AnakController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Anak;
use Illuminate\Http\Request;

class AnakController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:anak-list|anak-create|anak-edit|anak-delete', ['only' => ['index', 'store']]);
        $this->middleware('permission:anak-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:anak-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:anak-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $anaks = Anak::orderBy('nama_anak')->get();
        return view('admin.anak.index', compact('anaks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    { {
            return view('admin.anak.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_anak' => 'required',
            'tempat_lahir' => 'required',
            'tgl_lahir' => 'required',
            'jk' => 'required',
            'agama' => 'required',
            'pendidikan_anak' => 'required',
            'status' => 'required',
            'nama_ayah' => 'required',
            'nama_ibu' => 'required',
            'pekerjaan_ayah' => 'required',
            'pekerjaan_ibu' => 'required',
            'asal_daerah_ayah' => 'required',
            'asal_daerah_ibu' => 'required',
            'alamat_ortu' => 'required',
            'tgl_masuk' => 'required',
            'keterangan' => 'required',
        ]);

        Anak::create([
            'nama_anak' => $request->nama_anak,
            'tempat_lahir' => $request->tempat_lahir,
            'tgl_lahir' => $request->tgl_lahir,
            'jk' => $request->jk,
            'agama' => $request->agama,
            'pendidikan_anak' => $request->pendidikan_anak,
            'status' => implode($request->status),
            'nama_ayah' => $request->nama_ayah,
            'nama_ibu' => $request->nama_ibu,
            'pekerjaan_ayah' => $request->pekerjaan_ayah,
            'pekerjaan_ibu' => $request->pekerjaan_ibu,
            'asal_daerah_ayah' => $request->asal_daerah_ayah,
            'asal_daerah_ibu' => $request->asal_daerah_ibu,
            'alamat_ortu' => $request->alamat_ortu,
            'tgl_masuk' => $request->tgl_masuk,
            'keterangan' => $request->keterangan
        ]);

        return redirect()->route('anak.index')->with('success', 'Data Anak berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $anaks = Anak::findOrFail($id);
        return view('admin.anak.show', compact('anaks'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $anaks = Anak::findOrFail($id);
        return view('admin.anak.edit', compact('anaks'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_anak' => 'required',
            'tempat_lahir' => 'required',
            'tgl_lahir' => 'required',
            'jk' => 'required',
            'agama' => 'required',
            'pendidikan_anak' => 'required',
            'status' => 'required',
            'nama_ayah' => 'required',
            'nama_ibu' => 'required',
            'pekerjaan_ayah' => 'required',
            'pekerjaan_ibu' => 'required',
            'asal_daerah_ayah' => 'required',
            'asal_daerah_ibu' => 'required',
            'alamat_ortu' => 'required',
            'tgl_masuk' => 'required',
            'keterangan' => 'required',
        ]);

        $anaks = Anak::findOrFail($id);
        $anaks->nama_anak = $request->nama_anak;
        $anaks->tempat_lahir = $request->tempat_lahir;
        $anaks->tgl_lahir = $request->tgl_lahir;
        $anaks->jk = $request->jk;
        $anaks->agama = $request->agama;
        $anaks->pendidikan_anak = $request->pendidikan_anak;
        $anaks->status = implode($request->status);
        $anaks->nama_ayah = $request->nama_ayah;
        $anaks->nama_ibu = $request->nama_ibu;
        $anaks->pekerjaan_ayah = $request->pekerjaan_ayah;
        $anaks->pekerjaan_ibu = $request->pekerjaan_ibu;
        $anaks->asal_daerah_ayah = $request->asal_daerah_ayah;
        $anaks->asal_daerah_ibu = $request->asal_daerah_ibu;
        $anaks->alamat_ortu = $request->alamat_ortu;
        $anaks->tgl_masuk = $request->tgl_masuk;
        $anaks->keterangan = $request->keterangan;
        $anaks->save();

        return redirect()->route('anak.index')->with('success', 'Data Anak berhasil Diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Anak $anak)
    {
        $anak->delete();
        return redirect()->route('anak.index')->with('success', 'Data Anak Berhasil Dihapus');
    }
}

resources/views/admin/anak/create.blade.php
@extends('layouts.admin')
@section('main-content')

    <div class="d-flex justify-content-center" style="padding-top: 50px;">

        <div class="card" style="width: 70vw;">
            <div class="card-header text-center">
                <h5>Tambah Data Anak</h5>
            </div>
            <div class="card-body">
                <form action="{{ route('anak.store') }}" method="POST" accept="">
                    @csrf
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Nama Lengkap
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ old('nama_anak') }}" class="form-control" name="nama_anak"
                                placeholder="Masukan Nama Lengkap">
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Tempat Lahir
                        </div>
                        <div class="col-lg-9">
                            <input type="text" value="{{ old('tempat_lahir') }}" class="form-control"
                                name="tempat_lahir" placeholder="Masukan Tempat Lahir">
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Tanggal Lahir
                        </div>
                        <div class="col-lg-9">
                            <input type="date" value="{{ old('tgl_lahir') }}" class="form-control" name="tgl_lahir">
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Jenis Kelamin
                        </div>
                        <div class="col-lg-9">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="jk" value="Laki-laki">
                                <label class="form-check-label" for="gridRadios1">
                                    Laki-laki
                                </label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="jk" value="Perempuan">
                                <label class="form-check-label" for="gridRadios1">
                                    Perempuan
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Agama
                        </div>
                        <div class="col-lg-9">
                            <select class="form-select" name="agama" aria-label="Default select example">
                                <option selected>Pilih</option>
                                <option value="Islam">Islam</option>
                                <option value="Kristen">Kristen</option>
                                <option value="Hindu">Hindu</option>
                                <option value="Budha">Budha</option>
                                <option value="Khonghucu">Konghucu</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Pendidikan
                        </div>
                        <div class="col-lg-9">
                            <select class="form-select" name="pendidikan_anak">
                                <option selected>Pendidikan</option>
                                <option value="Islam">SD</option>
                                <option value="Kristen">SMP</option>
                                <option value="Hindu">SMK</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Status
                        </div>

                        <div class="col-lg-9">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="status[]" type="checkbox" value="Yatim">
                                <label class="form-check-label">Yatim</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="status[]" type="checkbox" value="Piatu">
                                <label class="form-check-label">Piatu</label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Nama Ayah
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ old('nama_ayah') }}" class="form-control" name="nama_ayah"
                                placeholder="Masukan Nama Ayah">
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Nama Ibu
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ old('nama_ibu') }}" class="form-control" name="nama_ibu"
                                placeholder="Masukan Nama Ibu">
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Pekerjaan Ayah
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ old('pekerjaan_ayah') }}" class="form-control"
                                name="pekerjaan_ayah" placeholder="Masukan Pekerjaan Ayah">
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Pekerjaan Ibu
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ old('pekerjaan_ibu') }}" class="form-control"
                                name="pekerjaan_ibu" placeholder="Masukan Pekerjaan Ibu">
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Asal Daerah Ayah
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ old('asal_daerah_ayah') }}" class="form-control"
                                name="asal_daerah_ayah" placeholder="Masukan Asal Daerah Ayah">
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Asal Daerah Ibu
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ old('asal_daerah_ibu') }}" class="form-control"
                                name="asal_daerah_ibu" placeholder="Masukan Asal Daerah Ibu">
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Alamat Orang Tua
                        </div>

                        <div class="col-lg-9">
                            <input type="textarea" value="{{ old('alamat_ortu') }}" class="form-control"
                                name="alamat_ortu" placeholder="Masukan Alamat Orang Tua">
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Tanggal Masuk
                        </div>
                        <div class="col-lg-9">
                            <input type="date" value="{{ old('tgl_masuk') }}" class="form-control" name="tgl_masuk">
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Keterangan
                        </div>

                        <div class="col-lg-9">
                            <input type="textarea" value="{{ old('keterangan') }}" class="form-control"
                                name="keterangan">
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-danger">Simpan Data</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>

@endsection

resources/views/admin/anak/edit.blade.php
@extends('layouts.admin')
@section('main-content')
    <div class="d-flex justify-content-center" style="padding-top: 50px;">

        <div class="card" style="width: 70vw">
            <div class="card-header text-center">
                <h5>Edit data</h5>
            </div>
            <div class="card-body">
                <form action="{{ route('anak.update', $anaks->id) }}" method="post" accept="">
                    @csrf
                    @method('PUT')
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Nama Lengkap
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ $anaks->nama_anak }}" class="form-control" name="nama_anak"
                                placeholder="Masukan Nama Lengkap" required>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Tempat Lahir
                        </div>
                        <div class="col-lg-9">
                            <input type="text" value="{{ $anaks->tempat_lahir }}" class="form-control"
                                name="tempat_lahir" placeholder="Masukan Tempat Lahir" required>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Tanggal Lahir
                        </div>
                        <div class="col-lg-9">
                            <input type="date" value="{{ $anaks->tgl_lahir }}" class="form-control" name="tgl_lahir"
                                required>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Jenis Kelamin
                        </div>
                        <div class="col-lg-9">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="jk" value="Laki-laki"
                                    {{ $anaks->jk == 'Laki-laki' ? 'checked' : '' }}>
                                <label class="form-check-label">
                                    Laki-laki
                                </label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="jk" value="Perempuan"
                                    {{ $anaks->jk == 'Perempuan' ? 'checked' : '' }}>
                                <label class="form-check-label">
                                    Perempuan
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Agama
                        </div>
                        <div class="col-lg-9">
                            <select class="form-select" name="agama" aria-label="Default select example">
                                <option selected>Pilih</option>
                                <option value="Islam" {{ $anaks->agama == 'Islam' ? 'selected' : '' }}>Islam</option>
                                <option value="Kristen" {{ $anaks->agama == 'Kristen' ? 'selected' : '' }}>Kristen
                                </option>
                                <option value="Hindu" {{ $anaks->agama == 'Hindu' ? 'selected' : '' }}>Hindu</option>
                                <option value="Budha" {{ $anaks->agama == 'Budha' ? 'selected' : '' }}>Budha</option>
                                <option value="Khonghucu" {{ $anaks->agama == 'Khonghucu' ? 'selected' : '' }}>Konghucu
                                </option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Pendidikan
                        </div>
                        <div class="col-lg-9">
                            <select class="form-select" name="pendidikan_anak">
                                <option selected>Pendidikan</option>
                                <option value="SD" {{ $anaks->pendidikan_anak == 'SD' ? 'selected' : '' }}>SD</option>
                                <option value="SMP" {{ $anaks->pendidikan_anak == 'SMP' ? 'selected' : '' }}>SMP</option>
                                <option value="SMK" {{ $anaks->pendidikan_anak == 'SMK' ? 'selected' : '' }}>SMK</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Status
                        </div>

                        <div class="col-lg-9">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="status[]" type="checkbox" value="Yatim"
                                    {{ $anaks->status == 'Yatim' ? 'checked' : '' }}>
                                <label class="form-check-label">Yatim</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" name="status[]" type="checkbox" value="Piatu"
                                    {{ $anaks->status == 'Piatu' ? 'checked' : '' }}>
                                <label class="form-check-label">Piatu</label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Nama Ayah
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ $anaks->nama_ayah }}" class="form-control" name="nama_ayah"
                                placeholder="Masukan Nama Ayah" required>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Nama Ibu
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ $anaks->nama_ibu }}" class="form-control" name="nama_ibu"
                                placeholder="Masukan Nama Ibu" required>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Pekerjaan Ayah
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ $anaks->pekerjaan_ayah }}" class="form-control"
                                name="pekerjaan_ayah" placeholder="Masukan Pekerjaan Ayah" required>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Pekerjaan Ibu
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ $anaks->pekerjaan_ibu }}" class="form-control"
                                name="pekerjaan_ibu" placeholder="Masukan Pekerjaan Ibu" required>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Asal Daerah Ayah
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ $anaks->asal_daerah_ayah }}" class="form-control"
                                name="asal_daerah_ayah" placeholder="Masukan Asal Daerah Ayah" required>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Asal Daerah Ibu
                        </div>

                        <div class="col-lg-9">
                            <input type="text" value="{{ $anaks->asal_daerah_ibu }}" class="form-control"
                                name="asal_daerah_ibu" placeholder="Masukan Asal Daerah Ibu" required>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Alamat Orang Tua
                        </div>

                        <div class="col-lg-9">
                            <input type="textarea" value="{{ $anaks->alamat_ortu }}" class="form-control"
                                name="alamat_ortu" placeholder="Masukan Alamat Orang Tua" required>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Tanggal Masuk
                        </div>
                        <div class="col-lg-9">
                            <input type="date" value="{{ $anaks->tgl_masuk }}" class="form-control" name="tgl_masuk"
                                required>
                        </div>
                    </div>

                    <div class="form-group d-flex">
                        <div class="col-lg-3">
                            Keterangan
                        </div>

                        <div class="col-lg-9">
                            <input type="textarea" value="{{ $anaks->keterangan }}" class="form-control"
                                name="keterangan" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-12">
                            <button type="submit" class="btn btn-danger">Ubah Data</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
@endsection