routes/web.php
<?php

use App\Http\Controllers\Admin\AnakController;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\KeuanganController;
use App\Http\Controllers\Admin\PemasukanController;
use App\Http\Controllers\Admin\PengeluaranController;
use App\Http\Controllers\Admin\ProgramController as AdminProgramController;
use App\Http\Controllers\Admin\PengurusController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\CKEditorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\UserController as ControllersUserController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::get('/', [AdminHomeController::class, 'index'])->name('admin.index');
    Route::prefix('keuangan')->group(function(){
        Route::get('/', [KeuanganController::class, 'index'])->name('keuangan.index');
        Route::get('pemasukan', [PemasukanController::class, 'index'])->name('pemasukan.index');
        Route::resource('pengeluaran', PengeluaranController::class)->except('show');
    });
    Route::resource('program', AdminProgramController::class)->except('show');
    Route::resource('pengurus', PengurusController::class);
    Route::resource('anak', AnakController::class);
    Route::resource('role', RoleController::class);
    Route::resource('user', UserController::class)->except('show');
});

Route::post('ckeditor/upload', [CKEditorController::class, 'upload'])->name('ckeditor.image-upload');
Route::get('{user}/profile', [ControllersUserController::class, 'show'])->name('profile');
Route::get('{user}/invoice', [InvoiceController::class, 'index'])->name('index.invoice');
Route::get('{user}/invoice/{invoice}', [InvoiceController::class, 'show'])->name('show.invoice');
Route::get('donation/pay/{invoice}', [DonationController::class, 'snap'])->name('donation.pay');
Route::post('donation/hook', [DonationController::class, 'hook'])->name('donation.hook');
Route::prefix('program')->group(function(){
    Route::get('/', [ProgramController::class, 'index'])->name('user-program.index');
    Route::get('{program}', [ProgramController::class, 'show'])->name('user-program.show');
    Route::middleware(['auth'])->group(function () {
    Route::post('{program}/donation', [ProgramController::class, 'store'])->name('donation.store');
    });
});

Auth::routes();

Route::get('/', HomeController::class)->name('home');

Route::get('/sto', fn () => storage_path());

app/Models/Pengurus.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pengurus extends Model
{
    use HasFactory;
    protected $fillable = ['nama', 'email', 'tempat_lahir', 'tanggal_lahir', 'jk', 'alamat', 'jabatan', 'telepon', 'agama', 'status', 'profile'];

    // public function user()
    // {
    //     return $this->belongsTo(User::class);
    // }

}

app/Http/Controllers/Admin/PengurusController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Pengurus\PengurusStoreRequest;
use App\Http\Requests\Pengurus\PengurusUpdateRequest;
use App\Models\Pengurus;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class PengurusController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:pengurus-list|pengurus-create|pengurus-edit|pengurus-delete', ['only' => ['index', 'store']]);
        $this->middleware('permission:pengurus-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:pengurus-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:pengurus-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $penguruses = Pengurus::get();
        return view('admin.pengurus.index', compact('penguruses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pengurus.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PengurusStoreRequest $request)
    {
    //    $user =  User::create([
    //         'name' => $request->nama,
    //         'email' => $request->email,
    //         'password' => bcrypt('admin')
    //     ]);

        if ($request->file('profile')) {
            $filename = Str::slug(now(), '') . '_Pengurus.' . $request->file('profile')->getClientOriginalExtension();
            $image = $request->file('profile')->storeAs('pengurus/profile', $filename);
        } else {
            $image = null;
        }

        Pengurus::create([
            'nama' => $request->nama,
            'tempat_lahir' => $request->tempat_lahir,
            'tanggal_lahir' => $request->tanggal_lahir,
            'jk' => $request->jk,
            'alamat' => $request->alamat,
            'jabatan' => $request->jabatan,
            'telepon' => $request->telepon,
            'email' => $request->email,
            'agama' => $request->agama,
            'status' => $request->status,
            'profile' => $image
        ]);

        return redirect()->route('pengurus.index')->with('success', 'Pengurus berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Pengurus $penguru)
    {
        return view('admin.pengurus.show', compact('penguru'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Pengurus $penguru)
    {
        return view('admin.pengurus.edit', compact('penguru'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PengurusUpdateRequest $request, Pengurus $penguru)
    {
        if ($request->file('profile')) {
            if ($request->oldImage) {
                Storage::delete($request->oldImage);
            }
            $filename = Str::slug(now(), '') . '_Pengurus.' . $request->file('profile')->getClientOriginalExtension();
            $image = $request->file('profile')->storeAs('pengurus/profile', $filename);
        } else {
            $image = $request->oldImage;
        }

        $penguru->update([
            'nama' => $request->nama,
            'tempat_lahir' => $request->tempat_lahir,
            'tanggal_lahir' => $request->tanggal_lahir,
            'jk' => $request->jk,
            'alamat' => $request->alamat,
            'jabatan' => $request->jabatan,
            'email' => $request->email,
            'telepon' => $request->telepon,
            'agama' => $request->agama,
            'status' => $request->status,
            'profile' => $image,
        ]);

        return redirect()->route('pengurus.index')->with('success', 'Pengurus Berhasil Diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pengurus $penguru)
    {
        if($penguru->profile){
            Storage::delete($penguru->profile);
        }

        $penguru->delete();

        return redirect()->route('pengurus.index');
    }
}

resources/views/admin/pengurus/create.blade.php
@extends('layouts.admin')

@section('main-content')
<div class="d-flex justify-content-center" style="padding-top: 50px">

        <div class="card" style="width: 70vw;">
            <form action="{{ route('pengurus.store') }}" method="post" enctype="multipart/form-data">
                @csrf
            <div class="card-body">
                <div class="card-title text-center">Tambah Data Pengurus</div>

                <div class="mb-4">
                    <label for="nama" class="form-label">Nama Pengurus</label>
                    <input type="text" name="nama" id="nama" class="form-control" value="{{ old('nama') }}">
                @error('nama')
                  <span class="text-danger">
                        <i>
                            {{ $message }}
                        </i>
                    </span>
                @enderror
                </div>

                <div class="mb-4">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" name="email" id="email" class="form-control" value="{{ old('email') }}">
                    @error('email')
                    <span class="text-danger">
                          <i>
                              {{ $message }}
                          </i>
                      </span>
                  @enderror
                </div>

                <div class="mb-4">
                    <label for="tempat_lahir" class="form-label">Tempat Lahir</label>
                    <input type="text" name="tempat_lahir" id="tempat_lahir" class="form-control" value="{{ old('tempat_lahir') }}">
                    @error('tempat_lahir')
                    <span class="text-danger">
                          <i>
                              {{ $message }}
                          </i>
                      </span>
                  @enderror
                </div>

                <div class="mb-4">
                    <label for="tanggal_ahir" class="form-label">Tanggal Lahir</label>
                    <input type="date" name="tanggal_lahir" id="tanggal_lahir" class="form-control" value="{{ old('tanggal_lahir') }}">
                    @error('tanggal_lahir')
                    <span class="text-danger">
                          <i>
                              {{ $message }}
                          </i>
                      </span>
                  @enderror
                </div>

                <div class="mb-4">
                    <label class="form-label">Jenis Kelamin</label>
                    <div class="form-check">
                    <input type="radio" name="jk" id="l" value="Laki-laki" class="form-check-input">
                    <label for="l" class="form-check-label">Laki-laki</label>
                    </div>
                    <div class="form-check">
                        <input type="radio" name="jk" id="p" value="Perempuan" class="form-check-input">
                        <label for="p" class="form-check-label">Perempuan</label>
                    </div>
                    @error('jk')
                    <span class="text-danger">
                          <i>
                              {{ $message }}
                          </i>
                      </span>
                  @enderror
                </div>

                <div class="mb-4">
                    <label for="alamat" class="form-label">Alamat</label>
                    <textarea name="alamat" id="alamat" cols="30" rows="10" class="form-control">{{ old('alamat') }}</textarea>
                    @error('alamat')
                    <span class="text-danger">
                          <i>
                              {{ $message }}
                          </i>
                      </span>
                  @enderror
                </div>

                <div class="mb-4">
                    <label for="jabatan" class="form-label">Jabatan</label>
                    <select name="jabatan" id="jabatan" class="form-control" required>
                        <option value="">Pilih Jabatan</option>
                        <option value="Dewan Pembina">Dewan Pembina</option>
                        <option value="Ketua">Ketua</option>
                        <option value="Sekertaris">Sekertaris</option>
                        <option value="Bendahara">Bendahara</option>
                        <option value="Bidang Logistik">Bidang Logistik</option>
                        <option value="Bidang Pendidikan">Bidang Pendidikan</option>
                        <option value="Bidang Kesehatan">Bidang Kesehatan</option>
                        <option value="Bidang Perawatan">Bidang Perawatan</option>
                        <option value="Bagian Asrama">Bagian Asrama</option>
                        <option value="Bagian Dapur">Bagian Dapur</option>
                        <option value="Bagian Pengasuh">Bagian Pengasuh</option>
                    </select>
                    @error('jabatan')
                    <span class="text-danger">
                          <i>
                              {{ $message }}
                          </i>
                      </span>
                  @enderror
                </div>

                <div class="mb-4">
                    <label for="telepon" class="form-label">No Telepon</label>
                    <input type="text" name="telepon" id="telepon" class="form-control" value="{{ old('telepon') }}">
                    @error('telepon')
                    <span class="text-danger">
                          <i>
                              {{ $message }}
                          </i>
                      </span>
                  @enderror
                </div>

                <div class="mb-4">
                    <label for="status" class="form-label">Status</label>
                    <input type="text" name="status" id="status" class="form-control" value="{{ old('status') }}">
                    @error('status')
                    <span class="text-danger">
                          <i>
                              {{ $message }}
                          </i>
                      </span>
                  @enderror
                </div>

                <div class="mb-4">
                    <label for="agama" class="form-label">Agama</label>
                    <select name="agama" id="agama" class="form-control">
                        <option value="">Pilih Agama</option>
                        <option value="Islam">Islam</option>
                        <option value="Kristen">Kristen</option>
                        <option value="Hindu">Hindu</option>
                        <option value="Budha">Budha</option>
                        <option value="Konghuchu">Konghuchu</option>
                    </select>
                    @error('agama')
                    <span class="text-danger">
                          <i>
                              {{ $message }}
                          </i>
                      </span>
                  @enderror
                </div>

                <img class="image-preview col-md-4">

                <div class="mb-4">
                    <label for="profile" class="form-label">Profile</label>
                    <input type="file" name="profile" id="profile" class="form-control" onchange="previewImage()">
                </div>

                <button type="submit" class="btn btn-primary">Tambah Data</button>
            </div>
            </form>

        </div>

</div>

<script>
    function previewImage(){
        const image = document.querySelector('#profile')
        const imgPreview = document.querySelector('.image-preview')

        imgPreview.style.display = 'block'

        const oFReader = new FileReader()
        oFReader.readAsDataURL(image.files[0])

        oFReader.onload = function(event){
            imgPreview.src = event.target.result
        }
    }
</script>
@endsection

resources/views/admin/pengurus/edit.blade.php
@extends('layouts.admin')

@section('main-content')
    <div class="d-flex justify-content-center" style="padding-top: 50px;">

            <div class="card" style="width: 70vw;">
                <form action="{{ route('pengurus.update', $penguru->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="card-body">
                        <div class="card-title text-center">
                            <h4>Edit Pengurus : {{ $penguru->nama }}</h4>
                        </div>

                        <input type="hidden" name="oldImage" value="{{ $penguru->profile }}">
                        <div class="mb-4">
                            <label for="nama" class="form-label">Nama Lengkap</label>
                            <input type="text" name="nama" id="nama" value="{{ $penguru->nama }}" class="form-control">
                            @error('nama')
                            <span class="text-danger italic">
                                {{ $message }}
                            </span>
                            @enderror
                        </div>

                        <div class="mb-4">
                            <label for="tempat_lahir" class="form-label">Tempat Lahir</label>
                            <input type="text" name="tempat_lahir" id="tempat_lahir" class="form-control"
                                value="{{ $penguru->tempat_lahir }}">
                                @error('tempat_lahir')
                                <span class="text-danger italic">
                                    {{ $message }}
                                </span>
                                @enderror
                        </div>

                        <div class="mb-4">
                            <label for="tanggal_lahir" class="form-label">Tanggal Lahir</label>
                            <input type="date" name="tanggal_lahir" id="tanggal_lahir" class="form-control"
                                value="{{ $penguru->tanggal_lahir }}">
                                @error('tanggal_lahir')
                                <span class="text-danger italic">
                                    {{ $message }}
                                </span>
                                @enderror
                        </div>

                        <div class="mb-4">
                            <div class="form-check">
                                <input type="radio" name="jk" id="l" value="Laki-laki" class="form-check-input"
                                    {{ $penguru->jk == 'Laki-laki' ? 'checked' : '' }}>
                                <label for="l" class="form-check-label">Laki-laki</label>
                            </div>
                            <div class="form-check">
                                <input type="radio" name="jk" id="p" value="Perempuan" class="form-check-input"
                                    {{ $penguru->jk == 'Perempuan' ? 'checked' : '' }}>
                                <label for="p" class="form-check-label">Perempuan</label>
                            </div>
                            @error('jk')
                            <span class="text-danger italic">
                                {{ $message }}
                            </span>
                            @enderror
                        </div>

                        <div class="mb-4">
                            <label for="alamat" class="form-label">Alamat</label>
                            <textarea name="alamat" id="" cols="30" rows="10"
                                class="form-control">{{ $penguru->alamat }}</textarea>
                                @error('alamat')
                                <span class="text-danger italic">
                                    {{ $message }}
                                </span>
                                @enderror
                        </div>

                        @if ($penguru->jabatan != 'Ketua')
                        <div class="mb-4">
                            <label for="jabatan" class="form-label">Jabatan</label>
                            <select name="jabatan" id="jabatan" class="form-control">
                                <option value="Dewan Pembina"
                                {{ $penguru->jabatan === 'Dewan Pembina' ? 'selected' : '' }}>Dewan Pembina</option>
                                <option value="Ketua" {{ $penguru->jabatan === 'Ketua' ? 'selected' : '' }}>Ketua
                                </option>
                                <option value="Sekertaris" {{ $penguru->jabatan === 'Sekertaris' ? 'selected' : '' }}>
                                    Sekertaris</option>
                                <option value="Bendahara" {{ $penguru->jabatan === 'Bendahara' ? 'selected' : '' }}>
                                    Bendahara</option>
                                <option value="Bidang Dewan PembinaLogistik"
                                    {{ $penguru->jabatan === 'Bidang Logistik' ? 'selected' : '' }}>Bidang Logistik
                                </option>
                                <option value="Bidang Pendidikan"
                                    {{ $penguru->jabatan === 'Bidang Pendidikan' ? 'selected' : '' }}>Bidang Pendidikan
                                </option>
                                <option value="Bidang Kesehatan"
                                    {{ $penguru->jabatan === 'Bidang Kesehatan' ? 'selected' : '' }}>Bidang Kesehatan
                                </option>
                                <option value="Bidang Perawatan"
                                    {{ $penguru->jabatan === 'Bidang Perawatan' ? 'selected' : '' }}>Bidang Perawatan
                                </option>
                                <option value="Bagian Asrama"
                                    {{ $penguru->jabatan === 'Bagian Asrama' ? 'selected' : '' }}>Bagian Asrama</option>
                                <option value="Bagian Dapur"
                                    {{ $penguru->jabatan === 'Bagian Dapur' ? 'selected' : '' }}>Bagian Dapur</option>
                                <option value="Bagian Pengasuh"
                                    {{ $penguru->jabatan === 'Bagian Pengasuh' ? 'selected' : '' }}>Bagian Pengasuh
                                </option>
                            </select>
                            @error('jabatan')
                            <span class="text-danger italic">
                                {{ $message }}
                            </span>
                            @enderror
                        </div>
                        @endif


                        <div class="mb-4">
                            <label for="agama" class="form-label">Agama</label>
                            <select name="agama" id="agama" class="form-control">
                                <option value="Islam" {{ $penguru->agama == 'Islam' ? 'selected' : '' }}>Islam</option>
                                <option value="Kristen" {{ $penguru->agama == 'Kristen' ? 'selected' : '' }}>Kristen
                                </option>
                                <option value="Hindu" {{ $penguru->agama == 'Hindu' ? 'selected' : '' }}>Hindu</option>
                                <option value="Budha" {{ $penguru->agama == 'Budha' ? 'selected' : '' }}>Budha</option>
                                <option value="Konghuchu" {{ $penguru->agama == 'Konghuchu' ? 'selected' : '' }}>
                                    Konghuchu</option>
                            </select>
                            @error('agama')
                            <span class="text-danger italic">
                                {{ $message }}
                            </span>
                            @enderror
                        </div>

                        <div class="mb-4">
                            <label for="telepon" class="form-label">Telepon</label>
                            <input type="text" name="telepon" id="telepon" class="form-control"
                                value="{{ $penguru->telepon }}">
                                @error('telepon')
                                <span class="text-danger italic">
                                    {{ $message }}
                                </span>
                                @enderror
                        </div>

                        <div class="mb-4">
                            <label for="Email" class="form-label">Email</label>
                            <input type="email" name="email" id="email" class="form-control"
                                value="{{ $penguru->email }}">
                                @error('email')
                                <span class="text-danger italic">
                                    {{ $message }}
                                </span>
                                @enderror
                        </div>

                        <div class="mb-4">
                            <label for="status" class="form-label">Status</label>
                            <input type="text" name="status" id="status" value="{{ $penguru->status }}"
                                class="form-control">
                                @error('status')
                                <span class="text-danger italic">
                                    {{ $message }}
                                </span>
                                @enderror
                        </div>

                        @if ($penguru->profile)
                            <img src="{{ asset('storage/' . $penguru->profile) }}" class="image-preview col-md-4 my-4">
                        @else
                            <img class="image-preview col-md-4">
                        @endif
                        <input type="file" name="profile" id="profile" class="form-control" onchange="previewImage()">

                        <button type="submit" class="btn btn-primary">Edit data pengurus</button>
                    </div>
                </form>
            </div>

        </div>

    <script>
        function previewImage() {
            const image = document.querySelector('#profile')
            const imgPreview = document.querySelector('.image-preview')

            imgPreview.style.display = 'block'

            const oFReader = new FileReader()
            oFReader.readAsDataURL(image.files[0])

            oFReader.onload = function(event) {
                imgPreview.src = event.target.result
            }
        }
    </script>
@endsection

resources/views/admin/pengurus/index.blade.php
@extends('layouts.admin')

@section('main-content')
    <div class="d-flex justify-content-center" style="padding-top: 50px;">

            <div class="card" style="width: 70vw;">
                <div class="card-body">
                    <div class="card-title text-center">
                        <h3>Data Pengurus</h3>
                    </div>
                    @can('pengurus-create')
                        <a href="{{ route('pengurus.create') }}" class="btn btn-primary my-2">Tambah data pengurus</a>
                    @endcan
                    <div class="table-responsive">
                        <table class="table table-striped">

                            <thead>
                                <tr>
                                    <th class="col">No</th>
                                    <th class="col">Nama Pengurus</th>
                                    <th class="col">Jabatan</th>
                                    <th class="col">Aksi</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach ($penguruses as $index => $pengurus)
                                    <tr>
                                        <td>{{ $index + 1 }}</td>
                                        <td>{{ $pengurus->nama }}</td>
                                        <td>{{ $pengurus->jabatan }}</td>
                                        <td class="d-flex">
                                            @can('pengurus-edit')
                                                <a href="{{ route('pengurus.edit', $pengurus->id) }}"
                                                    class="btn btn-primary">Edit</a>
                                            @endcan
                                            @can('pengurus-show')
                                            <a href="{{ route('pengurus.show', $pengurus->id) }}"
                                                class="btn btn-info text-white">Show</a>
                                            @endcan

                                            @can('pengurus-delete')
                                                <form action="{{ route('pengurus.destroy', $pengurus->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="submit" class="btn btn-danger"
                                                        onclick="return confirm('Apakah anda yakin akan menghapus data ini?')">Delete</button>
                                                </form>
                                            @endcan

                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>

                        </table>
                    </div>

                </div>
            </div>

    </div>
@endsection