routes/web.php
<?php

use App\Http\Controllers\Admin\AnakController;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\KeuanganController;
use App\Http\Controllers\Admin\PemasukanController;
use App\Http\Controllers\Admin\PengeluaranController;
use App\Http\Controllers\Admin\ProgramController as AdminProgramController;
use App\Http\Controllers\Admin\PengurusController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\CKEditorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\UserController as ControllersUserController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::get('/', [AdminHomeController::class, 'index'])->name('admin.index');
    Route::prefix('keuangan')->group(function(){
        Route::get('/', [KeuanganController::class, 'index'])->name('keuangan.index');
        Route::get('pemasukan', [PemasukanController::class, 'index'])->name('pemasukan.index');
        Route::resource('pengeluaran', PengeluaranController::class)->except('show');
    });
    Route::resource('program', AdminProgramController::class)->except('show');
    Route::resource('pengurus', PengurusController::class);
    Route::resource('anak', AnakController::class);
    Route::resource('role', RoleController::class);
    Route::resource('user', UserController::class)->except('show');
});

Route::post('ckeditor/upload', [CKEditorController::class, 'upload'])->name('ckeditor.image-upload');
Route::get('{user}/profile', [ControllersUserController::class, 'show'])->name('profile');
Route::get('{user}/invoice', [InvoiceController::class, 'index'])->name('index.invoice');
Route::get('{user}/invoice/{invoice}', [InvoiceController::class, 'show'])->name('show.invoice');
Route::get('donation/pay/{invoice}', [DonationController::class, 'snap'])->name('donation.pay');
Route::post('donation/hook', [DonationController::class, 'hook'])->name('donation.hook');
Route::prefix('program')->group(function(){
    Route::get('/', [ProgramController::class, 'index'])->name('user-program.index');
    Route::get('{program}', [ProgramController::class, 'show'])->name('user-program.show');
    Route::middleware(['auth'])->group(function () {
    Route::post('{program}/donation', [ProgramController::class, 'store'])->name('donation.store');
    });
});

Auth::routes();

Route::get('/', HomeController::class)->name('home');

Route::get('/sto', fn () => storage_path());

app/Http/Controllers/Admin/KeuanganController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Donation;
use App\Models\Spending;
use Illuminate\Http\Request;

class KeuanganController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:keungan-list|pengeluaran-create|pengeluaran-edit|pengeluaran-delete', ['only' => ['index', 'store']]);
        $this->middleware('permission:pengeluaran-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:pengeluaran-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:pengeluaran-delete', ['only' => ['destroy']]);
    }

    public function index()
    {
        $donations = Donation::get();
        $spendings = Spending::get();
        return view('admin.keuangan.index', compact('donations', 'spendings'));
    }

}

app/Http/Controllers/Admin/PengeluaranController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Spending;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Pengeluaran\PengeluaranStoreRequest;
use App\Http\Requests\Pengeluaran\PengeluaranUpdateRequest;

class PengeluaranController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $spendings = Spending::get();
        return view('admin.keuangan.pengeluaran.index', compact('spendings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.keuangan.pengeluaran.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PengeluaranStoreRequest $request)
    {
     Spending::create([
         'user_id' => Auth::user()->id,
         'description' => $request->description,
         'amount' => $request->amount,
         'release_date' => now()
     ]);

     return redirect()->route('pengeluaran.index')->with('success', 'Pengeluaran Berhasil Ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Spending $pengeluaran)
    {
        return view('admin.keuangan.pengeluaran.edit', compact('pengeluaran'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PengeluaranUpdateRequest $request, Spending $pengeluaran)
    {
        $pengeluaran->update([
            'amount' => $request->amount,
            'description' => $request->description
        ]);

        return redirect()->route('pengeluaran.index')->with('success', 'Pengeluaran Telah Berhasil Diedit');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Spending $pengeluaran)
    {
        $pengeluaran->delete();

        return redirect()->route('pengeluaran.index')->with('success', 'Pengeluaran Telah Dihapus');
    }
}

resources/views/admin/keuangan/pengeluaran/create.blade.php
@extends('layouts.admin')

@section('main-content')
    <div class="d-flex justify-content-center" style="padding-top: 50px;">
        <div class="card" style="width: 70vw;">
            <div class="card-body">
                <div class="card-title text-center">Tambah Pengeluaran</div>
                <form action="{{ route('pengeluaran.store') }}" method="post">
                @csrf
                <div class="form-group">
                    <label for="amount" class="form-label">Nominal Pengeluaran</label>
                    <input type="number" name="amount" id="amount" class="form-control" value="{{ old('amount') }}">
                    @error('amount')
                    <i class="text-danger">{{ $message }}</i>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="description" class="form-label">Detail Pengeluaran</label>
                    <textarea name="description" id="description"  class="form-control">{{ old('description') }}</textarea>
                    @error('description')
                    <i class="text-danger">{{ $message }}</i>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Tambah Pengeluaran</button>
            </form>


            </div>
        </div>
    </div>
@endsection

resources/views/admin/keuangan/pengeluaran/edit.blade.php
@extends('layouts.admin')

@section('main-content')
    <div class="d-flex justify-content-center" style="padding-top: 50px;">
        <div class="card" style="width: 70vw;">

            <div class="card-body">
                <div class="card-title text-center">
                    Edit Pengeluaran
                </div>

                <form action="{{ route('pengeluaran.update', $pengeluaran->id) }}" method="post">
                @csrf
                @method('put')
                <div class="form-group">
                    <label for="amount" class="form-label">Nominal Pengeluaran</label>
                    <input type="number" name="amount" id="amount" class="form-control" value="{{ $pengeluaran->amount }}">
                </div>

                <div class="form-group">
                    <label for="description" class="form-label">Detail Pengeluaran</label>
                    <textarea name="description" id="description"  class="form-control">{{ $pengeluaran->description }}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">Edit Pengeluaran</button>
            </form>
            </div>

        </div>
    </div>
@endsection

resources/views/admin/keuangan/pengeluaran/index.blade.php
@extends('layouts.admin')

@section('main-content')

<div class="d-flex justify-content-center" style="padding-top: 50px;">
    <div class="card" style="width: 70vw;">
        <div class="card-body">
            <div class="card-title text-center">
                Pengeluaran
            </div>
            <a href="{{ route('pengeluaran.create') }}" class="btn btn-primary mb-3">Tambah Pengeluaran</a>

            <div class="table-responsive">
                <table class="table table-stripped">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Yang Mengeluarkan</th>
                            <th>Nominal Pengeluaran</th>
                            <th>Detail Pengeluaran</th>
                            <th>Tanggal Pengeluaran</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($spendings as $index => $spending)
                        <tr>
                            <td>{{ $index+1 }}</td>
                            <td>{{ $spending->user->name }}</td>
                            <td>{{ $spending->amount }}</td>
                            <td>{{ $spending->description }}</td>
                            <td>{{ \Carbon\Carbon::parse($spending->release_date)->translatedFormat('d F Y, H:i') }}</td>
                            <td class="d-flex">
                                <a href="{{ route('pengeluaran.edit', $spending->id) }}" class="btn btn-primary">Edit</a>
                                <form action="{{ route('pengeluaran.destroy', $spending->id) }}" method="post">
                                @csrf
                                @method('delete')
                                <button type="submit" class="btn btn-danger">Hapus</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>

@endsection