routes/web.php
<?php

use App\Http\Controllers\Admin\AnakController;
use App\Http\Controllers\Admin\HomeController as AdminHomeController;
use App\Http\Controllers\Admin\KeuanganController;
use App\Http\Controllers\Admin\PemasukanController;
use App\Http\Controllers\Admin\PengeluaranController;
use App\Http\Controllers\Admin\ProgramController as AdminProgramController;
use App\Http\Controllers\Admin\PengurusController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\CKEditorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\ProgramController;
use App\Http\Controllers\UserController as ControllersUserController;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::middleware(['auth'])->prefix('admin')->group(function () {
    Route::get('/', [AdminHomeController::class, 'index'])->name('admin.index');
    Route::prefix('keuangan')->group(function(){
        Route::get('/', [KeuanganController::class, 'index'])->name('keuangan.index');
        Route::get('pemasukan', [PemasukanController::class, 'index'])->name('pemasukan.index');
        Route::resource('pengeluaran', PengeluaranController::class)->except('show');
    });
    Route::resource('program', AdminProgramController::class)->except('show');
    Route::resource('pengurus', PengurusController::class);
    Route::resource('anak', AnakController::class);
    Route::resource('role', RoleController::class);
    Route::resource('user', UserController::class)->except('show');
});

Route::post('ckeditor/upload', [CKEditorController::class, 'upload'])->name('ckeditor.image-upload');
Route::get('{user}/profile', [ControllersUserController::class, 'show'])->name('profile');
Route::get('{user}/invoice', [InvoiceController::class, 'index'])->name('index.invoice');
Route::get('{user}/invoice/{invoice}', [InvoiceController::class, 'show'])->name('show.invoice');
Route::get('donation/pay/{invoice}', [DonationController::class, 'snap'])->name('donation.pay');
Route::post('donation/hook', [DonationController::class, 'hook'])->name('donation.hook');
Route::prefix('program')->group(function(){
    Route::get('/', [ProgramController::class, 'index'])->name('user-program.index');
    Route::get('{program}', [ProgramController::class, 'show'])->name('user-program.show');
    Route::middleware(['auth'])->group(function () {
    Route::post('{program}/donation', [ProgramController::class, 'store'])->name('donation.store');
    });
});

Auth::routes();

Route::get('/', HomeController::class)->name('home');

Route::get('/sto', fn () => storage_path());

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'username',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getRouteKeyName()
    {
        return 'username';
    }
    
    public function pengurus()
    {
        return $this->belongsTo(Pengurus::class);
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\UserStoreRequest;
use App\Http\Requests\User\UserUpdateRequest;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:user-list|user-create|user-edit|user-delete', ['only' => ['index', 'store']]);
        $this->middleware('permission:user-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:user-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:user-delete', ['only' => ['destroy']]);
    }


    public function index(User $user)
    {
        $users = User::get();
        return view('admin.user.index', compact('users'));
    }

    public function create()
    {
        $roles = Role::pluck('name');
        return view('admin.user.create', compact('roles'));
    }

    public function store(UserStoreRequest $request)
    {
       $user =  User::create([
            'name' => $request->name,
            'email' => $request->email,
            'username' => $request->username,
            'password' => bcrypt($request->password)
        ]);

        $user->assignRole($request->roles);

        return redirect()->route('user.index')->with('success', 'Users Berhasil Ditambahkan');
    }


    public function edit(User $user)
    {
        $roles = Role::pluck('name')->all();
        $userRole = $user->roles->pluck('name')->all();

        return view('admin.user.edit', compact('user', 'userRole','roles'));
    }

    public function update(UserUpdateRequest $request, User $user)
    {
       $user->update([
            'name' => $request->name,
            'email' => $request->email,
        ]);

     DB::table('model_has_roles')->where('model_id', $user->id)->delete();



        $user->assignRole($request->roles);

        return redirect()->route('user.index')->with('success', 'User Berhasil di update');
    }

    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('user.index')->with('success', 'Data Berhasil dihapus');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Donation;
use Illuminate\Http\Request;
use App\Models\User;

class UserController extends Controller
{
    public function show(User $user)
    {
        $donations = Donation::get();
        // dd($donations);
        return view('user.profile', compact('user'));
    }

}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')

@section('main-content')

    <div class="d-flex justify-content-center" style="padding-top: 50px;">

        <div class="card" style="width: 70vw;">
            <div class="card-body">
                <div class="card-title text-center">Tambah Users</div>

                <form action="{{ route('user.store') }}" method="post">
                    @csrf

                    <div class="mb-4">
                        <label for="name" class="form label">Masukan Nama Lengkap</label>
                        <input type="text" name="name" id="name" class="form-control" value="{{ old('name') }}">
                        <span class="text-danger">
                            <i>
                                @error('name')
                                    {{ $message }}
                                @enderror
                            </i>
                        </span>
                    </div>

                    <div class="mb-4">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" name="email" id="email" class="form-control" value="{{ old('email') }}">
                        <span class="text-danger">
                            <i>
                                @error('email')
                                    {{ $message }}
                                @enderror
                            </i>
                        </span>
                    </div>

                    <div class="mb-4">
                        <label for="username" class="form-label">Username</label>
                        <input type="text" name="username" id="username" class="form-control"
                            value="{{ old('username') }}">
                        <span class="text-danger">
                            <i>
                                @error('username')
                                    {{ $message }}
                                @enderror
                            </i>
                        </span>
                    </div>

                    <div class="mb-4">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" name="password" id="password" class="form-control">
                        <span class="text-danger">
                            <i>
                                @error('password')
                                    {{ $message }}
                                @enderror
                            </i>
                        </span>
                    </div>

                    <div class="mb-4">
                        <label for="roles" class="form-label">Pilih Role</label>
                        <select name="roles[]" id="roles" class="form-control" multiple>
                            @foreach ($roles as $role)
                                <option value="{{ $role }}">{{ $role }}</option>
                            @endforeach
                        </select>
                        <span class="text-danger">
                            <i>
                                @error('roles')
                                    {{ $message }}
                                @enderror
                            </i>
                        </span>
                    </div>

                    <button type="submit" class="btn btn-primary">Tambah</button>

                </form>

            </div>
        </div>

    </div>

@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')

@section('main-content')

    <div class="d-flex justify-content-center" style="padding-top: 50px;">

        <div class="card" style="width: 70vw;">
            <div class="card-body">
                <div class="card-title text-center">Edit Users : <i>{{ $user->name }}</i></div>

                <form action="{{ route('user.update', $user->username) }}" method="post">
                    @csrf
                    @method('PUT')

                    <div class="mb-4">
                        <label for="name" class="form label">Masukan Nama Lengkap</label>
                        <input type="text" name="name" id="name" class="form-control" value="{{ $user->name }}">
                        <span class="text-danger">
                            <i>
                                @error('name')
                                    {{ $message }}
                                @enderror
                            </i>
                        </span>
                    </div>

                    <div class="mb-4">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" name="email" id="email" class="form-control" value="{{ $user->email }}">
                        <span class="text-danger">
                            <i>
                                @error('email')
                                    {{ $message }}
                                @enderror
                            </i>
                        </span>
                    </div>


                    <div class="mb-4">
                        <label for="roles" class="form-label">Pilih Role</label>
                        <select name="roles[]" id="roles" multiple='multiple' class="form-control">
                            @foreach ($userRole as $ur)
                                <option value="{{ $ur }}" selected>{{ $ur }}</option>
                            @endforeach
                            @foreach ($roles as $role)
                                <option value="{{ $role }}">{{ $role }}</option>
                            @endforeach
                        </select>
                        <span class="text-danger">
                            <i>
                                @error('roles')
                                    {{ $message }}
                                @enderror
                            </i>
                        </span>
                    </div>

                    <button type="submit" class="btn btn-primary">Edit User</button>

                </form>

            </div>
        </div>
        
    </div>

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('main-content')

    <div class="d-flex justify-content-center" style="padding-top: 50px;">

            <div class="card" style="width: 70vw">
                <div class="card-body">
                    <div class="card-title text-center">Management Users</div>
                    @can('user-create')
                    <a href="{{ route('user.create') }}" class="btn btn-primary my-4">Tambah Users</a>
                    @endcan

                    <div class="table-responsive">
                        <table class="table table-striped">

                            <thead>
                                <tr>
                                    <th class="col">No</th>
                                    <th class="col">Nama</th>
                                    <th class="col">Email</th>
                                    <th class="col">Role</th>
                                    <th class="col">Aksi</th>
                                </tr>
                            </thead>

                            <tbody>

                                @foreach ($users as $index => $user)

                                    <tr>

                                        <td>{{ $index + 1 }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>
                                            @if ($user->getRoleNames())
                                                @foreach ($user->getRoleNames() as $role)
                                                    <label for="" class="badge badge-success">{{ $role }}</label>
                                                @endforeach
                                            @endif
                                        </td>
                                        <td class="d-flex">
                                            @can('user-edit')
                                            <a href="{{ route('user.edit', $user->username) }}" class="btn btn-primary">Edit</a>
                                            @endcan
                                            @can('user-delete')
                                            <form action="{{ route('user.destroy', $user->username) }}" method="post">
                                            @csrf
                                            @method('delete')

                                            <button type="submit" class="btn btn-danger" onclick="return confirm('Apakah anda yakin akan menghapus data ini?')">Delete</button>
                                            </form>
                                            @endcan

                                        </td>

                                    </tr>

                                @endforeach

                            </tbody>

                        </table>
                    </div>

                </div>
            </div>

    </div>

@endsection